### ISSUE TITLE
Play random music from the MPD library

### ISSUE THREAD

**Issue by rimeno** [rccavalcanti/pifi-radio#7]
Hi,

In your previous version, it was possible to add a random button to play local MPD library shuffled, and it was a really cool bonus :) Do you think it's possible to add it again ?

**Comment by rc2dev** [comment]
Hi, thanks for the feedback!

I do consider re-implementing it, even more if someone finds it useful. Nice to know!

It is removed for now because I just re-wrote the whole frontend and gave that feature a low priority, as it was out of the original scope of the app. The focus was to improve the radio listening experience.

Also, if I implement that feature again, I want first to rethink its UX, to be richer and cohesive with the rest of the app.

I'm closing the issue, but feel free to drop a line if you want to add something.

Cheers!
